# Site settings
baseurl             = "https://zanadar.github.io/"
languageCode = "en-us"
title = "grumpcode"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Zander Mackie"
	description = "Computing and its discontents"
bio    = "In programming, as in everything else, to be in error is to be reborn. - Alan Perlis"
	# Enter optionally your twitter account
	twitter = "zanadar"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "GrumpyCoder"
	tweet = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/zandermackie"
    github   = "https://www.github.com/zanadar"
