baseurl = "https://www.example.com/"
title = "Zander Mackie"
author = "Zander Mackie"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "emacs"
pygmentscodefences  = true

[params]
  sitename = "Zander M."

[[menu.main]]
    name = "About"
    url  = "/about"