theme = "cocoa"
baseurl             = "https://you.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "docs"
author              = "Zander Mackie"
title               = "Code and its discontents"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "Zander Mackie"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "LOL computers"
email        = "zmackie@protonmail.com"
faviconfile  = "img/leaf.ico"
github       = "//github.com/zanadar"
highlightjs  = true
lang         = "en"
selfIntro    = "In programming, as in everything else, to be in error is to be reborn. - Alan Perlis"

# gravatar             = ""                # do not use in the same time as avatar
avatar                 = "img/noun_484238_cc.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"]            # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
