baseurl = "https://www.zmackie.com/"
title = "Zander M."
author = "Zander Mackie"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "emacs"
pygmentscodefences  = true

paginate                 = 1
paginatePath             = "page"

[params]
  sitename = "Zander M."

[[menu.main]]
    name = "About"
    url  = "/about"
