baseurl = "https://zanadar.github.io"
title = "CodeGrump"
theme = "hugo-theme-vec"
languageCode = "en-us"
paginate = 20
googleAnalytics = "UA-57408564-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  Keywords = ""
  Description = "Computing and its discontents"
  Avater = "img/noun_80531_cc.png"
  SelfIntro = "Like punning, programming is a play on words. - A. Perlis"
  Email = "zmackie@protonmail.com"

  GithubID = "zanadar"
  TwitterID = "zandermackie"
